/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m.b.m.k2dframeanalysis;

import java.text.DecimalFormat;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ma739918
 */
public class DeflectionsFram extends javax.swing.JFrame {
    
    public MbmkMatrix myMatrix;
    public static double[][] Deflections; 

    /**
     * Creates new form DeflicionsFram
     */
    public DeflectionsFram() {
        initComponents();
    }
    public DeflectionsFram(double D[][]) {
        initComponents();
        Deflections = D;
    }
    public MainScreen ms;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Deflections = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable_Deflections.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Joint", "D1(mm) _ X Direction", "D2(mm) _ Y Direction", "D3(rad) _Rotation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Deflections);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
          DefaultTableModel model = (DefaultTableModel) jTable_Deflections.getModel();

          DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
          centerRenderer.setHorizontalAlignment( JLabel.CENTER );
          jTable_Deflections.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
          jTable_Deflections.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
          jTable_Deflections.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
          jTable_Deflections.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );

          int NumberOfJoint = Deflections.length / 3;
          for (int i=0 ; i<=NumberOfJoint-1 ;i++){
              model.addRow(new Object[]{String.valueOf(i),Format(1000*Deflections[(i+1)*3-3][0],"0.00E00"),Format(1000*Deflections[(i+1)*3-2][0],"0.00E00"),Format(1*Deflections[(i+1)*3-1][0],"0.00E00")});
          }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
    }
    
    public  double Format(double value, String decimals){
        DecimalFormat df2 = new DecimalFormat( decimals );
         double newValue = new Double(df2.format(value)).doubleValue();
         return newValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_Deflections;
    // End of variables declaration//GEN-END:variables
}
